# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build Plugin

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Create Pre/Post Build Override
      run: |
        echo '<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003"><Target Name="PostBuildEvent"/><Target Name="PreBuildEvent" /></Project>' > SupressBuildEvents.csproj
    
    - uses: actions/checkout@v3
      with: 
        repository: SuchByte/Macro-Deck
        ref: refs/heads/main
        path: macro-deck
        
    - name: Remove COM Reference
      working-directory: ./macro-deck
      run: dotnet remove reference NetFwTypeLib
        
    - name: Restore dependencies
      working-directory: ./macro-deck
      run: dotnet restore -property:EnableWindowsTargeting=true
      
    - name: Build
      working-directory: ./macro-deck
      run: dotnet build --no-restore -property:EnableWindowsTargeting=true -property:SignAssembly=false -property:CustomAfterMicrosoftCommonTargets=../SupressBuildEvents.proj
  
    - name: Test
      working-directory: ./macro-deck
      run: dotnet test --no-build --verbosity normal
    - uses: actions/checkout@v3
      with: 
        path: plugin
        
    - name: Move dll into location
      working-directory: ./macro-deck
      run: |
        cp 'obj\Release\netcoreapp3.1\Macro Deck 2.dll' '../plugin/Macro Deck 2.dll'
        
    - name: Enable Windows Targeting
      uses: Mudlet/xmlstarlet-action@2459d21dc77b093ef78e3c3f8bfd256e2c2c2b73
      with:
        args: ed -P --delete //Project/PostBuild --delete //Project/PreBuild ./plugin/*.csproj
      
    - name: Restore dependencies
      working-directory: ./plugin
      run: dotnet restore /p:EnableWindowsTargeting=true
    
    - name: Build
      working-directory: ./plugin
      run: dotnet build --no-restore /p:EnableWindowsTargeting=true -property:CustomAfterMicrosoftCommonTargets=../SupressBuildEvents.proj
    
    - name: Test
      working-directory: ./plugin
      run: dotnet test --no-build --verbosity normal
