name: Macro Deck Plugin Build

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:    
    runs-on: windows-latest
    
    steps:     
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        
      - uses: actions/checkout@v2
        with: 
          name: SuchByte/Macro-Deck
          ref: refs/heads/main
          path: macro-deck
      
      - name: Build Solution
        working-directory: ./macro-deck
        run: dotnet build -c Release
          
      - name: Move dll into location
        working-directory: ./macro-deck
        run: |
          cp 'obj\Release\netcoreapp3.1\Macro Deck 2.dll' '$c\Program Files\Macro Deck\'
          
      - uses: actions/checkout@v2
        with: 
          path: plugin

      - name: Build Solution
        working-directory: ./plugin
        run: dotnet build -c Release
              
  zip-files:
    needs: build
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: obj/Release/netcoreapp3.1 Plugin.xml Icon.png README.md LICENSE
          dest: RecklessBoon.MacroDeck.GPUZ.zip
