name: Macro Deck Plugin Build

on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      tag: 
        description: "Tag for release"
        required: true
        type: string

jobs:
  build:    
    runs-on: windows-latest
    
    steps:     
      # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2
        
      - uses: actions/checkout@v2
        with: 
          repository: SuchByte/Macro-Deck
          ref: refs/heads/main
          path: macro-deck
          
      # Restore the application to populate the obj folder with RuntimeIdentifiers
      - name: Restore the application
        run: msbuild /t:Restore /p:Configuration=Release
        working-directory: ./macro-deck
        
      - name: Build the application
        run: msbuild /t:rebuild /verbosity:diag /p:Configuration=Release
        working-directory: ./macro-deck
          
      - uses: actions/checkout@v2
        with: 
          path: plugin

      # Restore the application to populate the obj folder with RuntimeIdentifiers
      - name: Restore the application
        run: msbuild /t:Restore /p:Configuration=Release
        working-directory: ./plugin
        
      - name: Build the application
        run: msbuild /t:rebuild /verbosity:diag /p:Configuration=Release
        working-directory: ./plugin
              
      - name: Package into zip
        uses: papeloto/action-zip@v1
        with:
          #files: plugin/dist plugin/Plugin.xml plugin/Icon.png plugin/README.md plugin/LICENSE
          files: plugin
          dest: RecklessBoon.MacroDeck.GPUZ.zip
          
      - name: Upload files to a GitHub release
        # You may pin to the exact commit or the version.
        # uses: svenstaro/upload-release-action@483c1e56f95e88835747b1c7c60581215016cbf2
        uses: svenstaro/upload-release-action@2.2.1
        with:
          # GitHub token.
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          # Local file to upload.
          file: ./RecklessBoon.MacroDeck.GPUZ.zip
          # Tag to use as a release.
          tag: ${{ github.event.inputs.tag }}
          # Overwrite the release in case it already exists.
          overwrite: true
