name: Macro Deck Plugin Build

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:    
    runs-on: windows-latest
    
    steps:     
      # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2
        
      - uses: actions/checkout@v2
        with: 
          repository: SuchByte/Macro-Deck
          ref: refs/heads/main
          path: macro-deck
          
      # Restore the application to populate the obj folder with RuntimeIdentifiers
      - name: Restore the application
        run: msbuild /t:Restore /p:Configuration=Release
        working-directory: ./macro-deck
          
      - uses: actions/checkout@v2
        with: 
          path: plugin

      # Restore the application to populate the obj folder with RuntimeIdentifiers
      - name: Restore the application
        run: msbuild /t:Restore /p:Configuration=Release
        working-directory: ./plugin
              
  zip-files:
    needs: build
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: obj/Release/netcoreapp3.1 Plugin.xml Icon.png README.md LICENSE
          dest: RecklessBoon.MacroDeck.GPUZ.zip
