name: Macro Deck Plugin Build

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:    
    runs-on: windows-latest
    
    steps:     
      - uses: actions/checkout@v2
        with: 
          path: plugin
      
      - uses: actions/checkout@v2
        with: 
          name: SuchByte/Macro-Deck
          ref: refs/heads/master
          path: macro-deck
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        
      - name: Move into Macro Deck dir
        run: cd $GITHUB_WORKSPACE/macro-deck

      - name: Build Solution
        run: dotnet build -c Release
        
      - name: Move dll into location
        run: cp '$GITHUB_WORKSPACE/macro-deck/obj/Release/netcoreapp3.1/Macro Deck 2.dll' '$c/Program Files/Macro Deck/'
        
      - name: Move into Macro Deck dir
        run: cd $GITHUB_WORKSPACE/plugin

      - name: Build Solution
        run: dotnet build -c Release
              
  zip-files:
    needs: build
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: obj/Release/netcoreapp3.1 Plugin.xml Icon.png README.md LICENSE
          dest: RecklessBoon.MacroDeck.GPUZ.zip
