# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build Plugin

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Install XMLStarlet
      run: sudo apt-get install -y xmlstarlet
    
    - uses: actions/checkout@v3
      with: 
        repository: SuchByte/Macro-Deck
        ref: refs/heads/main
        path: macro-deck
        
    - name: Remove Pre Build Targets
      working-directory: ./macro-deck
      run : |
        xmlstarlet ed -P -L --delete '//Target[@Name="PreBuild"]' ./macro-deck/*.csproj
        xmlstarlet ed -P -L --delete '//Target[@Name="PostBuild"]' ./macro-deck/*.csproj
        
    - name: Check CSPROJ
      working-directory: ./macro-deck
      run: cat *.csproj
        
    - name: Remove COM Reference
      working-directory: ./macro-deck
      run: dotnet remove reference NetFwTypeLib
        
    - name: Restore dependencies
      working-directory: ./macro-deck
      run: dotnet restore -property:EnableWindowsTargeting=true
      
    - name: Build
      working-directory: ./macro-deck
      run: dotnet build --no-restore -property:EnableWindowsTargeting=true -property:SignAssembly=false
  
    - name: Test
      working-directory: ./macro-deck
      run: dotnet test --no-build --verbosity normal
      
    - uses: actions/checkout@v3
      with: 
        path: plugin
      
    - name: Remove Pre Build Targets
      uses: Mudlet/xmlstarlet-action@master
      with:
        args: ed -P -L --delete '//Target[@Name="PreBuild"]' ./plugin/*.csproj
        
    - name: Remove Post Build Targets
      uses: Mudlet/xmlstarlet-action@master
      with:
        args: ed -P -L --delete '//Target[@Name="PostBuild"]' ./plugin/*.csproj
      
    - name: Move dll into location
      working-directory: ./macro-deck
      run: |
        cp 'obj\Release\netcoreapp3.1\Macro Deck 2.dll' '../plugin/Macro Deck 2.dll'
      
    - name: Restore dependencies
      working-directory: ./plugin
      run: dotnet restore /p:EnableWindowsTargeting=true
    
    - name: Build
      working-directory: ./plugin
      run: dotnet build --no-restore /p:EnableWindowsTargeting=true
      
    - name: Test
      working-directory: ./plugin
      run: dotnet test --no-build --verbosity normal
