name: Macro Deck Plugin Build

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:    
    runs-on: windows-latest
    
    steps:     
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x' # SDK Version to use; x will use the latest version of the 3.1 channel
        
      - uses: actions/checkout@v2
        with: 
          repository: SuchByte/Macro-Deck
          ref: refs/heads/main
          path: macro-deck
      
      - name: Build Solution
        run: dotnet build -c Release
        working-directory: ./macro-deck
          
      - uses: actions/checkout@v2
        with: 
          path: plugin

      - name: Build Solution
        run: dotnet build -c Release
        working-directory: ./plugin
              
  zip-files:
    needs: build
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: obj/Release/netcoreapp3.1 Plugin.xml Icon.png README.md LICENSE
          dest: RecklessBoon.MacroDeck.GPUZ.zip
